name: pytest

on:
 push:
    branches:
    - main
 pull_request:
    branches:
    - main

jobs:
  test:
    name: Run tests with ${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests (non-distributed)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          export PATH=$HOME/.local/bin:$PATH

          uv run pytest tests/
